# Generated by Django 5.0.2 on 2024-09-07 14:55

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmauser',
            name='pharm_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='PharmacistClicked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pharmauser')),
            ],
            managers=[
                ('countobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='Pharmmodels',
        ),
    ]
