# Generated by Django 5.1.2 on 2024-10-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacistclicked',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
