# Generated by Django 5.0.2 on 2024-08-03 16:17

import datetime
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip', models.CharField(max_length=100)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonuses', models.IntegerField(default=0)),
                ('date_gained', models.DateField(default=datetime.datetime(2024, 8, 3, 16, 17, 39, 477009, tzinfo=datetime.timezone.utc))),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='client_with_bonus')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='item name')),
                ('description', models.CharField(max_length=1000, verbose_name='item description')),
                ('price', models.CharField(max_length=20, verbose_name='item price')),
                ('discount', models.IntegerField(default=0, verbose_name='item discount')),
                ('date_entered', models.DateField(default=datetime.datetime(2024, 8, 3, 16, 17, 39, 474143, tzinfo=datetime.timezone.utc), verbose_name='date item entered')),
                ('quantity', models.IntegerField(default=0, verbose_name='item quantity')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_information', models.CharField(blank=True, max_length=1000, null=True, verbose_name='product information')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.categories', verbose_name='item category')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('date_sold', models.DateField(default=django.utils.timezone.now)),
                ('product', models.ManyToManyField(to='display.items')),
            ],
        ),
        migrations.CreateModel(
            name='MostSearched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime(2024, 8, 3, 16, 17, 39, 477009, tzinfo=datetime.timezone.utc))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.items')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='ordered quantity')),
                ('total_price', models.IntegerField(default=0)),
                ('ordered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.items', verbose_name='item_ordered')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ordering', to=settings.AUTH_USER_MODEL, verbose_name='user ordering')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRatingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_stars', models.IntegerField(blank=True, null=True, verbose_name='number stars')),
                ('date_created', models.DateField(default=datetime.datetime(2024, 8, 3, 16, 17, 39, 477009, tzinfo=datetime.timezone.utc), editable=False)),
                ('product_review', models.CharField(blank=True, max_length=3000, null=True, verbose_name='product review')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_product', to='display.items')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.CharField(blank=True, max_length=300, null=True, verbose_name='user review')),
                ('date', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user review')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='display.items', verbose_name='product name')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip', models.CharField(max_length=100)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=datetime.datetime(2024, 8, 3, 16, 17, 39, 493264, tzinfo=datetime.timezone.utc), verbose_name='order date')),
                ('total_price', models.IntegerField()),
                ('loyalty_discount', models.CharField(max_length=100, verbose_name='loyalty discount')),
                ('ordered', models.BooleanField(default=False)),
                ('saved_address', models.BooleanField(default=False)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='display.billingaddress')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.payment')),
                ('items', models.ManyToManyField(to='display.orderitems')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='display.shippingaddress')),
            ],
        ),
    ]
