# Generated by Django 5.0.2 on 2024-09-16 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_alter_bonus_date_gained_alter_items_date_entered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='date_gained',
            field=models.DateField(default=datetime.datetime(2024, 9, 16, 3, 19, 36, 73834, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='items',
            name='categories',
        ),
        migrations.AlterField(
            model_name='items',
            name='date_entered',
            field=models.DateField(default=datetime.datetime(2024, 9, 16, 3, 19, 36, 73834, tzinfo=datetime.timezone.utc), verbose_name='date item entered'),
        ),
        migrations.AlterField(
            model_name='mostsearched',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 16, 3, 19, 36, 73834, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 16, 3, 19, 36, 89460, tzinfo=datetime.timezone.utc), verbose_name='order date'),
        ),
        migrations.AlterField(
            model_name='productratingreview',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 9, 16, 3, 19, 36, 73834, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AddField(
            model_name='items',
            name='categories',
            field=models.ManyToManyField(to='display.categories'),
        ),
    ]
