# Generated by Django 5.0.2 on 2024-09-17 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_items_slug_alter_bonus_date_gained_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='categories',
        ),
        migrations.AddField(
            model_name='categories',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='categories',
            name='item',
            field=models.ManyToManyField(to='display.items'),
        ),
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='date_gained',
            field=models.DateField(default=datetime.datetime(2024, 9, 17, 12, 53, 12, 995758, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='date_entered',
            field=models.DateField(default=datetime.datetime(2024, 9, 17, 12, 53, 12, 991757, tzinfo=datetime.timezone.utc), verbose_name='date item entered'),
        ),
        migrations.AlterField(
            model_name='mostsearched',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 17, 12, 53, 12, 995758, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 17, 12, 53, 13, 7758, tzinfo=datetime.timezone.utc), verbose_name='order date'),
        ),
        migrations.AlterField(
            model_name='productratingreview',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 9, 17, 12, 53, 12, 991757, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
