# Generated by Django 5.1.2 on 2024-10-19 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0009_alter_bonus_date_gained_alter_items_date_entered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('sexual health', 'sexual health'), ('skin health', 'skin health'), ('immune system', 'immune system'), ('category2', 'category2'), ('category', 'category')], default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bonus',
            name='date_gained',
            field=models.DateField(default=datetime.datetime(2024, 10, 19, 21, 20, 5, 80783, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='date_entered',
            field=models.DateField(default=datetime.datetime(2024, 10, 19, 21, 20, 5, 65159, tzinfo=datetime.timezone.utc), verbose_name='date item entered'),
        ),
        migrations.AlterField(
            model_name='mostsearched',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 10, 19, 21, 20, 5, 80783, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 19, 21, 20, 5, 112039, tzinfo=datetime.timezone.utc), verbose_name='order date'),
        ),
        migrations.AlterField(
            model_name='productratingreview',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 10, 19, 21, 20, 5, 80783, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
