# Generated by Django 5.1.2 on 2024-10-20 16:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0013_rename_user_order_customer_alter_bonus_date_gained_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order2', to=settings.AUTH_USER_MODEL, verbose_name='user order1'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='date_gained',
            field=models.DateField(default=datetime.datetime(2024, 10, 20, 16, 52, 43, 37225, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='date_entered',
            field=models.DateField(default=datetime.datetime(2024, 10, 20, 16, 52, 43, 30225, tzinfo=datetime.timezone.utc), verbose_name='date item entered'),
        ),
        migrations.AlterField(
            model_name='mostsearched',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 10, 20, 16, 52, 43, 38225, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 20, 16, 52, 43, 67230, tzinfo=datetime.timezone.utc), verbose_name='order date'),
        ),
        migrations.AlterField(
            model_name='productratingreview',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 10, 20, 16, 52, 43, 36228, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
