# Generated by Django 5.1.2 on 2024-10-20 16:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0014_remove_order_customer_order_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='date_gained',
            field=models.DateField(default=datetime.datetime(2024, 10, 20, 16, 54, 8, 173605, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='date_entered',
            field=models.DateField(default=datetime.datetime(2024, 10, 20, 16, 54, 8, 157981, tzinfo=datetime.timezone.utc), verbose_name='date item entered'),
        ),
        migrations.AlterField(
            model_name='mostsearched',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 10, 20, 16, 54, 8, 173605, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 20, 16, 54, 8, 204859, tzinfo=datetime.timezone.utc), verbose_name='order date'),
        ),
        migrations.AlterField(
            model_name='productratingreview',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 10, 20, 16, 54, 8, 173605, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
