# Generated by Django 5.1.2 on 2024-10-24 00:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0018_remove_order_client_alter_bonus_date_gained_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsclicked',
            name='client',
        ),
        migrations.RemoveField(
            model_name='productsclicked',
            name='item',
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='items',
            name='item_image',
        ),
        migrations.RemoveField(
            model_name='items',
            name='product_information',
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='apartment_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='date_gained',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client with Bonus'),
        ),
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('sexual health', 'Sexual Health'), ('skin health', 'Skin Health'), ('immune system', 'Immune System')], max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='date_entered',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='items',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='items',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mostsearched',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='loyalty_discount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loyalty Discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Ordered'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.items', verbose_name='Item Ordered'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Ordered Quantity'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to=settings.AUTH_USER_MODEL, verbose_name='User Ordering'),
        ),
        migrations.AlterField(
            model_name='productratingreview',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='productratingreview',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productratingreview',
            name='number_stars',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Stars'),
        ),
        migrations.AlterField(
            model_name='productratingreview',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='display.items'),
        ),
        migrations.AlterField(
            model_name='productratingreview',
            name='product_review',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Product Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='display.items', verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviews',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='User Review'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='apartment_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='ProductsClicked',
        ),
    ]
